### PR TITLE
Tranduções português-Brasil

### PR DESCRIPTION
**Pull request by hotdesc**
Brazilian portuguese translate

### CODE REVIEW

**Comment by amma35** [comment]
Have you translated on transifex? https://www.transifex.com/tsmr/GLPI_mydashboard

**Comment by amma35** [comment]
fix in https://github.com/InfotelGLPI/mydashboard/commit/48fc12fbb62dea647e3ab2252eb61b772b03df75

**Comment by hotdesc** [comment]
I sent an invitation

**Comment by amma35** [comment]
I accepted.
Tell me when you could translate the untranslated words, I would update then.

**Comment by hotdesc** [comment]
Done and revised 

I improved

**Comment by amma35** [comment]
Updated in the commit: https://github.com/InfotelGLPI/mydashboard/commit/3c8f3712eedb92093d3bfa374212ba376814afae

**Pull request closed without merging**
